#!/bin/sh -e
# Copyright (c) 2016 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='xiwi'
DESCRIPTION='Installs lmms'
HOSTBIN='startlmms'
CHROOTBIN='startlmms'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
# Update database
apt-get update || true

install lmms

TIPS="$TIPS
You can start lmms via the startlmms host command: sudo startlmms
"
