#!/bin/sh -e
# Copyright (c) 2016 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='plex-server'
DESCRIPTION='Installs plex media server unauthorized application store'
HOSTBIN='startplexu'
CHROOTBIN='startplexu'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:

# Update database
apt-get update || true

install unzip
